# Generated by Django 5.2.7 on 2025-10-20 02:55

from django.db import migrations
from django.contrib.auth import get_user_model

def asignar_usuario_a_tareas_existentes(apps, schema_editor):
    """Asigna un usuario por defecto a las tareas existentes que no tienen usuario."""
    Gestor_tareas = apps.get_model('tareas', 'Gestor_tareas')
    User = get_user_model()
    
    # Obtener el primer superusuario disponible, o crear uno si no existe
    try:
        usuario_por_defecto = User.objects.filter(is_superuser=True).first()
        if not usuario_por_defecto:
            # Si no hay superusuarios, crear uno por defecto
            usuario_por_defecto = User.objects.create_user(
                username='admin_default',
                password='admin123',
                is_superuser=True,
                is_staff=True
            )
    except:
        # Si hay algún error, simplemente no hacer nada
        # Las tareas mantendrán usuario=None hasta que se asignen manualmente
        return
    
    # Asignar el usuario por defecto a todas las tareas sin usuario
    Gestor_tareas.objects.filter(usuario__isnull=True).update(usuario=usuario_por_defecto)

def reverse_asignar_usuario(apps, schema_editor):
    """Operación reversa - opcional."""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_gestor_tareas_usuario'),
    ]

    operations = [
        migrations.RunPython(asignar_usuario_a_tareas_existentes, reverse_asignar_usuario),
    ]
