# Generated by Django 5.2.7 on 2025-10-20 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20251019_2355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestor_tareas',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='gestor_tareas',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
